In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def mean_squared_error(y_true, y_pred):
    return np.mean((y_true - y_pred)**2)

def sigmoid_derivative(x):
    return x * (1 - x)

# Initialize random weights and biases
np.random.seed(42)
input_size = 2
hidden_size = 4
output_size = 2

weights_input_hidden = np.random.rand(input_size, hidden_size)
biases_hidden = np.zeros((1, hidden_size))

weights_hidden_output = np.random.rand(hidden_size, output_size)
biases_output = np.zeros((1, output_size))

# Dummy input data
X = np.array([[0.5, 0.7]])

# Dummy target values
y_true = np.array([[0.6, 0.8]])

# Forward propagation
hidden_layer_input = np.dot(X, weights_input_hidden) + biases_hidden
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + biases_output
y_pred = output_layer_input  # Linear activation for output layer in regression task

# Calculate Mean Squared Error
loss = mean_squared_error(y_true, y_pred)

# Backward propagation
# Calculate gradients
output_error = y_pred - y_true
output_delta = output_error  # Derivative of MSE with respect to the output

hidden_layer_error = np.dot(output_delta, weights_hidden_output.T)
hidden_delta = hidden_layer_error * sigmoid_derivative(hidden_layer_output)

# Update weights and biases using gradients and learning rate
learning_rate = 0.01

weights_hidden_output -= learning_rate * np.dot(hidden_layer_output.T, output_delta)
biases_output -= learning_rate * np.sum(output_delta, axis=0, keepdims=True)

weights_input_hidden -= learning_rate * np.dot(X.T, hidden_delta)
biases_hidden -= learning_rate * np.sum(hidden_delta, axis=0, keepdims=True)

# Now, the weights and biases have been updated based on the backward propagation step

# Print results
print("Input:\n", X)
print("Target:\n", y_true)
print("Predicted:\n", y_pred)
print("Mean Squared Error:", loss)


Input:
 [[0.5 0.7]]
Target:
 [[0.6 0.8]]
Predicted:
 [[0.98718939 1.28699947]]
Mean Squared Error: 0.19354205474785396
